/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "pbRPC.pb-c.h"
void   freerds__pbrpc__rpcbase__init
                     (Freerds__Pbrpc__RPCBase         *message)
{
  static Freerds__Pbrpc__RPCBase init_value = FREERDS__PBRPC__RPCBASE__INIT;
  *message = init_value;
}
size_t freerds__pbrpc__rpcbase__get_packed_size
                     (const Freerds__Pbrpc__RPCBase *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__pbrpc__rpcbase__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t freerds__pbrpc__rpcbase__pack
                     (const Freerds__Pbrpc__RPCBase *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__pbrpc__rpcbase__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t freerds__pbrpc__rpcbase__pack_to_buffer
                     (const Freerds__Pbrpc__RPCBase *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__pbrpc__rpcbase__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Freerds__Pbrpc__RPCBase *
       freerds__pbrpc__rpcbase__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Freerds__Pbrpc__RPCBase *)
     protobuf_c_message_unpack (&freerds__pbrpc__rpcbase__descriptor,
                                allocator, len, data);
}
void   freerds__pbrpc__rpcbase__free_unpacked
                     (Freerds__Pbrpc__RPCBase *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__pbrpc__rpcbase__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue freerds__pbrpc__rpcbase__rpcstatus__enum_values_by_number[3] =
{
  { "SUCCESS", "FREERDS__PBRPC__RPCBASE__RPCSTATUS__SUCCESS", 0 },
  { "FAILED", "FREERDS__PBRPC__RPCBASE__RPCSTATUS__FAILED", 1 },
  { "NOTFOUND", "FREERDS__PBRPC__RPCBASE__RPCSTATUS__NOTFOUND", 2 },
};
static const ProtobufCIntRange freerds__pbrpc__rpcbase__rpcstatus__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex freerds__pbrpc__rpcbase__rpcstatus__enum_values_by_name[3] =
{
  { "FAILED", 1 },
  { "NOTFOUND", 2 },
  { "SUCCESS", 0 },
};
const ProtobufCEnumDescriptor freerds__pbrpc__rpcbase__rpcstatus__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "freerds.pbrpc.RPCBase.RPCSTATUS",
  "RPCSTATUS",
  "Freerds__Pbrpc__RPCBase__RPCSTATUS",
  "freerds.pbrpc",
  3,
  freerds__pbrpc__rpcbase__rpcstatus__enum_values_by_number,
  3,
  freerds__pbrpc__rpcbase__rpcstatus__enum_values_by_name,
  1,
  freerds__pbrpc__rpcbase__rpcstatus__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const protobuf_c_boolean freerds__pbrpc__rpcbase__is_response__default_value = 0;
static const Freerds__Pbrpc__RPCBase__RPCSTATUS freerds__pbrpc__rpcbase__status__default_value = FREERDS__PBRPC__RPCBASE__RPCSTATUS__SUCCESS;
static const ProtobufCFieldDescriptor freerds__pbrpc__rpcbase__field_descriptors[6] =
{
  {
    "tag",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Freerds__Pbrpc__RPCBase, tag),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isResponse",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Freerds__Pbrpc__RPCBase, isresponse),
    NULL,
    &freerds__pbrpc__rpcbase__is_response__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Freerds__Pbrpc__RPCBase, status),
    &freerds__pbrpc__rpcbase__rpcstatus__descriptor,
    &freerds__pbrpc__rpcbase__status__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgType",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Freerds__Pbrpc__RPCBase, msgtype),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Freerds__Pbrpc__RPCBase, has_payload),
    PROTOBUF_C_OFFSETOF(Freerds__Pbrpc__RPCBase, payload),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errorDescription",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Freerds__Pbrpc__RPCBase, errordescription),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned freerds__pbrpc__rpcbase__field_indices_by_name[] = {
  5,   /* field[5] = errorDescription */
  1,   /* field[1] = isResponse */
  3,   /* field[3] = msgType */
  4,   /* field[4] = payload */
  2,   /* field[2] = status */
  0,   /* field[0] = tag */
};
static const ProtobufCIntRange freerds__pbrpc__rpcbase__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor freerds__pbrpc__rpcbase__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "freerds.pbrpc.RPCBase",
  "RPCBase",
  "Freerds__Pbrpc__RPCBase",
  "freerds.pbrpc",
  sizeof(Freerds__Pbrpc__RPCBase),
  6,
  freerds__pbrpc__rpcbase__field_descriptors,
  freerds__pbrpc__rpcbase__field_indices_by_name,
  1,  freerds__pbrpc__rpcbase__number_ranges,
  (ProtobufCMessageInit) freerds__pbrpc__rpcbase__init,
  NULL,NULL,NULL    /* reserved[123] */
};
