/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "ICP.pb-c.h"
void   freerds__icp__is_channel_allowed_request__init
                     (Freerds__Icp__IsChannelAllowedRequest         *message)
{
  static Freerds__Icp__IsChannelAllowedRequest init_value = FREERDS__ICP__IS_CHANNEL_ALLOWED_REQUEST__INIT;
  *message = init_value;
}
size_t freerds__icp__is_channel_allowed_request__get_packed_size
                     (const Freerds__Icp__IsChannelAllowedRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__is_channel_allowed_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t freerds__icp__is_channel_allowed_request__pack
                     (const Freerds__Icp__IsChannelAllowedRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__is_channel_allowed_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t freerds__icp__is_channel_allowed_request__pack_to_buffer
                     (const Freerds__Icp__IsChannelAllowedRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__is_channel_allowed_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Freerds__Icp__IsChannelAllowedRequest *
       freerds__icp__is_channel_allowed_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Freerds__Icp__IsChannelAllowedRequest *)
     protobuf_c_message_unpack (&freerds__icp__is_channel_allowed_request__descriptor,
                                allocator, len, data);
}
void   freerds__icp__is_channel_allowed_request__free_unpacked
                     (Freerds__Icp__IsChannelAllowedRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__is_channel_allowed_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   freerds__icp__is_channel_allowed_response__init
                     (Freerds__Icp__IsChannelAllowedResponse         *message)
{
  static Freerds__Icp__IsChannelAllowedResponse init_value = FREERDS__ICP__IS_CHANNEL_ALLOWED_RESPONSE__INIT;
  *message = init_value;
}
size_t freerds__icp__is_channel_allowed_response__get_packed_size
                     (const Freerds__Icp__IsChannelAllowedResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__is_channel_allowed_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t freerds__icp__is_channel_allowed_response__pack
                     (const Freerds__Icp__IsChannelAllowedResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__is_channel_allowed_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t freerds__icp__is_channel_allowed_response__pack_to_buffer
                     (const Freerds__Icp__IsChannelAllowedResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__is_channel_allowed_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Freerds__Icp__IsChannelAllowedResponse *
       freerds__icp__is_channel_allowed_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Freerds__Icp__IsChannelAllowedResponse *)
     protobuf_c_message_unpack (&freerds__icp__is_channel_allowed_response__descriptor,
                                allocator, len, data);
}
void   freerds__icp__is_channel_allowed_response__free_unpacked
                     (Freerds__Icp__IsChannelAllowedResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__is_channel_allowed_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   freerds__icp__ping_request__init
                     (Freerds__Icp__PingRequest         *message)
{
  static Freerds__Icp__PingRequest init_value = FREERDS__ICP__PING_REQUEST__INIT;
  *message = init_value;
}
size_t freerds__icp__ping_request__get_packed_size
                     (const Freerds__Icp__PingRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__ping_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t freerds__icp__ping_request__pack
                     (const Freerds__Icp__PingRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__ping_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t freerds__icp__ping_request__pack_to_buffer
                     (const Freerds__Icp__PingRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__ping_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Freerds__Icp__PingRequest *
       freerds__icp__ping_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Freerds__Icp__PingRequest *)
     protobuf_c_message_unpack (&freerds__icp__ping_request__descriptor,
                                allocator, len, data);
}
void   freerds__icp__ping_request__free_unpacked
                     (Freerds__Icp__PingRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__ping_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   freerds__icp__ping_response__init
                     (Freerds__Icp__PingResponse         *message)
{
  static Freerds__Icp__PingResponse init_value = FREERDS__ICP__PING_RESPONSE__INIT;
  *message = init_value;
}
size_t freerds__icp__ping_response__get_packed_size
                     (const Freerds__Icp__PingResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__ping_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t freerds__icp__ping_response__pack
                     (const Freerds__Icp__PingResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__ping_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t freerds__icp__ping_response__pack_to_buffer
                     (const Freerds__Icp__PingResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__ping_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Freerds__Icp__PingResponse *
       freerds__icp__ping_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Freerds__Icp__PingResponse *)
     protobuf_c_message_unpack (&freerds__icp__ping_response__descriptor,
                                allocator, len, data);
}
void   freerds__icp__ping_response__free_unpacked
                     (Freerds__Icp__PingResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &freerds__icp__ping_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor freerds__icp__is_channel_allowed_request__field_descriptors[1] =
{
  {
    "ChannelName",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Freerds__Icp__IsChannelAllowedRequest, channelname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned freerds__icp__is_channel_allowed_request__field_indices_by_name[] = {
  0,   /* field[0] = ChannelName */
};
static const ProtobufCIntRange freerds__icp__is_channel_allowed_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor freerds__icp__is_channel_allowed_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "freerds.icp.IsChannelAllowedRequest",
  "IsChannelAllowedRequest",
  "Freerds__Icp__IsChannelAllowedRequest",
  "freerds.icp",
  sizeof(Freerds__Icp__IsChannelAllowedRequest),
  1,
  freerds__icp__is_channel_allowed_request__field_descriptors,
  freerds__icp__is_channel_allowed_request__field_indices_by_name,
  1,  freerds__icp__is_channel_allowed_request__number_ranges,
  (ProtobufCMessageInit) freerds__icp__is_channel_allowed_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor freerds__icp__is_channel_allowed_response__field_descriptors[1] =
{
  {
    "ChannelAllowed",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Freerds__Icp__IsChannelAllowedResponse, channelallowed),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned freerds__icp__is_channel_allowed_response__field_indices_by_name[] = {
  0,   /* field[0] = ChannelAllowed */
};
static const ProtobufCIntRange freerds__icp__is_channel_allowed_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor freerds__icp__is_channel_allowed_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "freerds.icp.IsChannelAllowedResponse",
  "IsChannelAllowedResponse",
  "Freerds__Icp__IsChannelAllowedResponse",
  "freerds.icp",
  sizeof(Freerds__Icp__IsChannelAllowedResponse),
  1,
  freerds__icp__is_channel_allowed_response__field_descriptors,
  freerds__icp__is_channel_allowed_response__field_indices_by_name,
  1,  freerds__icp__is_channel_allowed_response__number_ranges,
  (ProtobufCMessageInit) freerds__icp__is_channel_allowed_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor freerds__icp__ping_request__field_descriptors[0] =
{
};
static const unsigned freerds__icp__ping_request__field_indices_by_name[] = {
};
#define freerds__icp__ping_request__number_ranges NULL
const ProtobufCMessageDescriptor freerds__icp__ping_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "freerds.icp.PingRequest",
  "PingRequest",
  "Freerds__Icp__PingRequest",
  "freerds.icp",
  sizeof(Freerds__Icp__PingRequest),
  0,
  freerds__icp__ping_request__field_descriptors,
  freerds__icp__ping_request__field_indices_by_name,
  0,  freerds__icp__ping_request__number_ranges,
  (ProtobufCMessageInit) freerds__icp__ping_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor freerds__icp__ping_response__field_descriptors[1] =
{
  {
    "pong",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Freerds__Icp__PingResponse, pong),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned freerds__icp__ping_response__field_indices_by_name[] = {
  0,   /* field[0] = pong */
};
static const ProtobufCIntRange freerds__icp__ping_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor freerds__icp__ping_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "freerds.icp.PingResponse",
  "PingResponse",
  "Freerds__Icp__PingResponse",
  "freerds.icp",
  sizeof(Freerds__Icp__PingResponse),
  1,
  freerds__icp__ping_response__field_descriptors,
  freerds__icp__ping_response__field_indices_by_name,
  1,  freerds__icp__ping_response__number_ranges,
  (ProtobufCMessageInit) freerds__icp__ping_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue freerds__icp__msgtype__enum_values_by_number[2] =
{
  { "IsChannelAllowed", "FREERDS__ICP__MSGTYPE__ISCHANNELALLOWED", 1 },
  { "Ping", "FREERDS__ICP__MSGTYPE__PING", 2 },
};
static const ProtobufCIntRange freerds__icp__msgtype__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex freerds__icp__msgtype__enum_values_by_name[2] =
{
  { "IsChannelAllowed", 0 },
  { "Ping", 1 },
};
const ProtobufCEnumDescriptor freerds__icp__msgtype__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "freerds.icp.MSGTYPE",
  "MSGTYPE",
  "Freerds__Icp__MSGTYPE",
  "freerds.icp",
  2,
  freerds__icp__msgtype__enum_values_by_number,
  2,
  freerds__icp__msgtype__enum_values_by_name,
  1,
  freerds__icp__msgtype__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
