/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef fdsapi_CONSTANTS_H
#define fdsapi_CONSTANTS_H

#include "fdsapi_types.h"

namespace freerds {

class fdsapiConstants {
 public:
  fdsapiConstants();

};

extern const fdsapiConstants g_fdsapi_constants;

} // namespace

#endif
