/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "fdsapi_constants.h"

namespace freerds {

const fdsapiConstants g_fdsapi_constants;

fdsapiConstants::fdsapiConstants() {
}

} // namespace

